module.exports = {
  LIKE_CREATE: "LIKE_CREATE",
  LIKE_DELETE: "LIKE_DELETE", // premium only
  COMMENT_CREATE: "COMMENT_CREATE",
  COMMENT_DELETE: "COMMENT_DELETE", // premium only
  FOLLOW_CREATE: "FOLLOW_CREATE",
  FOLLOW_DELETE: "FOLLOW_DELETE", // premium only
  SYSTEM_MESSAGE: "SYSTEM_MESSAGE",
  FEED_MENTION: "FEED_MENTION",
  COMMENT_MENTION: "COMMENT_MENTION",
}