version: 2.1
jobs:
  clone-and-run:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "13:bb:be:5d:53:d0:38:82:0b:eb:42:51:a2:00:77:ca"
      - run:
          name: "Main"
          command: | 
            ssh -o "StrictHostKeyChecking no" root@$SERVER_IP 
            sudo kill -9 `sudo lsof -t -i:80`
            cd Matchify2
            git pull
            tmux \
            new-session  "sudo node ."
            exit

workflows:
  say-hello-workflow:
    jobs:
      - clone-and-run
